<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"> 
<link rel="stylesheet" href="/static/css/nav/navigator.min.css"> 
<link rel="stylesheet" href="/static/css/nav/item-catalog-navbar.css">
<link rel="stylesheet" href="/static/css/nav/animation/animation.css">
<link rel="stylesheet" type="text/css" href="/static/css/modal/default.css" />
<link rel="stylesheet" type="text/css" href="/static/css/modal/component.css" />
<link rel="stylesheet" type="text/css" href="/static/css/custom/custom.css" />